completed 01, 02 tasks
elenaalkoli/js_automation_course_hw pull request #4
Opened 2024-06-06 13:38 UTC by elenaalkoli

2024-06-06 20:01 UTC, anatoly-karpovich requested changes

2024-06-06 20:01 UTC, anatoly-karpovich commented on hw_05/task_02.js
> +  if (!(i % 3) && !(i % 5)) { // if true && true (или можно !(i % 15) сразу)
А где деление на 3 и на 5 по очереди?)

2024-06-07 21:20 UTC, elenaalkoli commented on hw_05/task_02.js
> +  if (!(i % 3) && !(i % 5)) { // if true && true (или можно !(i % 15) сразу)
thanks, I've added. Also added task_03

2024-06-08 13:45 UTC, anatoly-karpovich requested changes

2024-06-08 13:45 UTC, anatoly-karpovich commented on hw_05/task_02.js
> +        console.log(`${i} is devided on 3 and 5 without a remainder`)
```suggestion
    if (!(i % 3) && !(i % 5)) { // if true && true (или можно !(i % 15) сразу)
        console.log(`${i} is devided on 3 and 5 without a remainder`
   } else if (!(i % 3)) {
        console.log(`${i} is devided on 3 without a remainder`)
    } else  if (!(i % 5)) {
        console.log(`${i} is devided on 5 without a remainder`)
    }
```

2024-06-08 13:45 UTC, anatoly-karpovich commented on hw_05/task_03.js
> +        result += String.fromCharCode(codeOfSymbol) //обратно
You are not handling boundary values as Z and z for positive offset and A\a for negative one

Try ZzZ for offset === 1, implementation should return AaA

2024-06-11 21:39 UTC, anatoly-karpovich approved these changes

2024-06-12 08:27 UTC, merged